name = "infinex-patron-test"
preset = "patron-purchase"
version = "1.0.0"
description = "Smart Contracts used for Infinex Patron Purchase App"

# pnpm cannon build infinex-patron/patron-purchase-app/staging/infinex-patron-test.polygon.toml --chain-id 137 --dry-run

[var.PATRON]
depends = []
PATRON_DEPLOYER = "0x6298551D56F825B3b6c3350D32129Ffd3cFb198C"
FUNDS_DESTINATION = "0x85aCda8bA2b2eB1a311426C6CE60942FC6E8a7BE"
AUTHORIZED_SIGNER = "0xf56DE57c251257C05F83CCE338A46bd5D3a3E506"
PATRON_FINAL_OWNER = "0x85aCda8bA2b2eB1a311426C6CE60942FC6E8a7BE" 
# AUTHORIZED VAULTS
VAULT_1 = "0x85aCda8bA2b2eB1a311426C6CE60942FC6E8a7BE"
VAULT_2 = "0x6298551D56F825B3b6c3350D32129Ffd3cFb198C"
# AUTHORIZED TOKENS
USDC_TOKEN = "0x3c499c542cef5e3811e1192ce70d8cc03d5c3359" 
USDT_TOKEN = "0xc2132d05d31c914a87c6611c10748aeb04b58e8f"  
USDC_E_TOKEN = "0x2791Bca1f2de4661ED88A30C99A7a9449Aa84174"
DAI_TOKEN = "0x8f3cf7ad23cd3cadbd9735aff958023239c6a063"
ETHER = "0x0000000000000000000000000000000000000000"

[clone.infinexPatronPurchase]
depends = ['var.PATRON']
options.PATRON_DEPLOYER = "<%= settings.PATRON_DEPLOYER %>"
options.FUNDS_DESTINATION = "<%= settings.FUNDS_DESTINATION %>"
options.PATRON_PURCHASE_SALT = "PATRON_PURCHASE_SALT_1_0_10"
source = "infinex:1.0.0@patron-purchase"
target = "infinex:1.0.0@patron-purchase"

[invoke.PatronPointOfPurchaseInitialize]
target = ["infinexPatronPurchase.PatronPointOfPurchase"]
func = "initialize"
args = [
    "<%= settings.PATRON_DEPLOYER %>",
    "<%= settings.FUNDS_DESTINATION %>",
    [
        "<%= settings.AUTHORIZED_SIGNER %>",
    ],
    [
        "<%= settings.USDC_TOKEN %>",
        "<%= settings.USDT_TOKEN %>",
        "<%= settings.USDC_E_TOKEN %>",
        "<%= settings.DAI_TOKEN %>",
        "<%= settings.ETHER %>"
    ],
    [
        "<%= settings.VAULT_1 %>",
        "<%= settings.VAULT_2 %>"
    ],
]
depends = [
    "clone.infinexPatronPurchase",
]

[invoke.PatronPurchaseVaultInitialize]
target = ["infinexPatronPurchase.PatronPurchaseVault"]
func = "initialize"
args = ["<%= settings.PATRON_DEPLOYER %>", "<%= settings.FUNDS_DESTINATION %>"]
depends = [
    "clone.infinexPatronPurchase",
]

[invoke.PatronPurchaseVaultInitialize2]
target = ["infinexPatronPurchase.PatronPurchaseVault2"]
func = "initialize"
args = ["<%= settings.PATRON_DEPLOYER %>", "<%= settings.FUNDS_DESTINATION %>"]
depends = [
    "clone.infinexPatronPurchase",
]

# Transfer Ownership

[invoke.transferOwnershipPatronPurchaseAppBeacon]
target = ["infinexPatronPurchase.PatronPurchaseAppBeacon"]
func = "transferOwnership"
args = ["<%= settings.PATRON_FINAL_OWNER %>"]
from = "<%= settings.PATRON_DEPLOYER %>"

[invoke.transferOwnershipPatronPointOfPurchase]
target = ["infinexPatronPurchase.PatronPointOfPurchase"]
func = "transferOwnership"
args = ["<%= settings.PATRON_FINAL_OWNER %>"]
from = "<%= settings.PATRON_DEPLOYER %>"

[invoke.transferOwnershipPatronPurchaseVault]
target = ["infinexPatronPurchase.PatronPurchaseVault"]
func = "transferOwnership"
args = ["<%= settings.PATRON_FINAL_OWNER %>"]
from = "<%= settings.PATRON_DEPLOYER %>"

[invoke.transferOwnershipPatronPurchaseVault2]
target = ["infinexPatronPurchase.PatronPurchaseVault2"]
func = "transferOwnership"
args = ["<%= settings.PATRON_FINAL_OWNER %>"]
from = "<%= settings.PATRON_DEPLOYER %>"

# Accept Ownership

[invoke.acceptOwnershipPatronPurchaseAppBeacon]
target = ["infinexPatronPurchase.PatronPurchaseAppBeacon"]
func = "acceptOwnership"
from = "<%= settings.PATRON_FINAL_OWNER %>"
depends = ["invoke.transferOwnershipPatronPurchaseAppBeacon"]

[invoke.acceptOwnershipPatronPointOfPurchase]
target = ["infinexPatronPurchase.PatronPointOfPurchase"]
func = "acceptOwnership"
from = "<%= settings.PATRON_FINAL_OWNER %>"
depends = ["invoke.transferOwnershipPatronPointOfPurchase"]

[invoke.acceptOwnershipPatronPurchaseVault]
target = ["infinexPatronPurchase.PatronPurchaseVault"]
func = "acceptOwnership"
from = "<%= settings.PATRON_FINAL_OWNER %>"
depends = ["invoke.transferOwnershipPatronPurchaseVault"]

[invoke.acceptOwnershipPatronPurchaseVault2]
target = ["infinexPatronPurchase.PatronPurchaseVault2"]
func = "acceptOwnership"
from = "<%= settings.PATRON_FINAL_OWNER %>"
depends = ["invoke.transferOwnershipPatronPurchaseVault2"]


