name = "infinex-multichain"
preset = "craterun"
version = "1.0.0"
description = "Smart Contracts used for the Infinex Craterun Campaign"

# --chain-id 8453

[var.Deploy]
CRATERUN_DEPLOYER = "0x3F768E3aC5eE75A2F39CFD7d72Eb3a40Bddb5ecB"
CRATERUN_KEEPER= "0xD29C3ba6a1fF5FB3048Dd7C77D79C55D4F72Bd06"
CRATE_POINTS_NAME = "InfinexCratePoints"

[pull.InfinexMultichain]
source = "infinex-multichain:1.0.0staging@O2"

[clone.InfinexCraterun]
options.DEPLOYER = "<%= settings.CRATERUN_DEPLOYER %>"
options.ENTROPY_ = "0x6E7D74FA7d5c90FEF9F0512987605a6d546181Bb"         # Pyth Entropy contract address
options.ENTROPY_PROVIDER = "0x52DeaA1c84233F7bb8C8A45baeDE41091c616506" # Pyth Entropy provider address
options.FORWARDER= "<%= imports.InfinexMultichain.imports.infinex.contracts.Forwarder.address %>"         # Forwarder contract address
options.ACCOUNT_FACTORY = "<%= imports.InfinexMultichain.imports.infinex.contracts.AccountFactory.address %>" # AccountFactory contract address
options.CRATE_POINTS_NAME = "<%= settings.CRATE_POINTS_NAME %>"
options.TOTAL_CRATES = "5000000" # 5 million
options.REWARDS_DURATION = "604800" # 1 week
source = "infinex:1.0.0@craterun"
target = "infinex:1.0.0@craterun"

# ---------- Settings post deployment parameters  ---------- #

# ---------- Initializers ---------- #

[invoke.CratePointsInitialize]
target = ["InfinexCraterun.CratePointsProxy"]
func = "initialize"
args = ["<%= settings.CRATERUN_DEPLOYER %>", "<%= settings.CRATE_POINTS_NAME %>"]

# ---------- CratePoints Minters ---------- #

[invoke.CratePointsSetMinterForDeployer]
target=["InfinexCraterun.CratePointsProxy"]
func="setAuthorizedMinter"
args=["<%= settings.CRATERUN_DEPLOYER  %>", true]
from = "<%= settings.CRATERUN_DEPLOYER %>"

[invoke.CratePointsSetMinterForCrateOpener]
target=["InfinexCraterun.CratePointsProxy"]
func="setAuthorizedMinter"
args=["<%= imports.InfinexCraterun.contracts.CrateOpener.address  %>", true]
from = "<%= settings.CRATERUN_DEPLOYER %>"

[invoke.CratePointsSetMinterForStakingRewards]
target=["InfinexCraterun.CratePointsProxy"]
func="setAuthorizedMinter"
args=["<%= imports.InfinexCraterun.contracts.CtPStakingRewards.address  %>", true]
from = "<%= settings.CRATERUN_DEPLOYER %>"

# ---------- Keepers ---------- #

[invoke.CrateOpenerSetKeeper]
target=["InfinexCraterun.CrateOpener"]
func="setAuthorizedKeeper"
args=["<%= settings.CRATERUN_KEEPER  %>", true]
from = "<%= settings.CRATERUN_DEPLOYER %>"

[invoke.StakingRewardsSetKeeper]
target=["InfinexCraterun.CtPStakingRewards"]
func="setAuthorizedKeeper"
args=["<%= settings.CRATERUN_KEEPER  %>", true]
from = "<%= settings.CRATERUN_DEPLOYER %>"




