#  pnpm cannon build infinex-omnibus/staging/infinex-omnibus-test.blast.toml --chain-id 81457 --dry-run
#  pnpm cannon publish infinex-omnibus-test:3.0.0@omnibus --chain-id 81457 --exclude-cloned

name = "infinex-omnibus-test"
version = "3.0.0"
preset = "omnibus"
description = "All Infinex Deployments"

[pull.AccountFactoryV1]
source = "infinex-account-factory-test:1.0.0@main"

[pull.CoreV3]
source = "infinex-core-test:3.0.0@core"

[pull.CardRun]
source = "infinex-cardrun-test:1.0.0@cardrun"