name = "infinex-core-test"
version = "3.0.2"
preset = "core"
description = "Infinex Core Deployments"
#  pnpm cannon build infinex-multichain/testnets/infinex-multichain-blast-sepolia.toml --chain-id 168587773 --dry-run --upgrade-from 
#  pnpm cannon publish infinex-core-test:latest@core --chain-id 168587773 --exclude-cloned
#  pnpm cannon verify infinex-core-test:latest@core --chain-id 168587773 --api-key 

[var.Deploy]
DEPLOYER = "0x6298551D56F825B3b6c3350D32129Ffd3cFb198C"
REVENUE_POOL = "0x6298551D56F825B3b6c3350D32129Ffd3cFb198C"
PLACEHOLDER_ADDRESS="0x6298551D56F825B3b6c3350D32129Ffd3cFb198C" # Placeholder address used for when an address is required but not used
WITHDRAWAL_FEE_USDC = "<%= parseUnits(String(0), 6) %>"
TRUSTED_RECOVERY_KEEPER = "0x6298551D56F825B3b6c3350D32129Ffd3cFb198C"

[pull.AccountFactory]
source = "infinex-account-factory-test:1.0.0@main"

[clone.infinex]
source = "infinex:3.0.0@core"
target = "infinex:3.0.0@core"
options.CORE_SALT = "INFINEX_0_1_7"
options.CORE_DEPLOYER = "<%= settings.DEPLOYER %>"
options.CORE_INITIAL_PROXY_IMPLEMENTATION = "<%= imports.AccountFactory.imports.AccountFactory.contracts.InitialProxyImplementation.address %>"
options.CORE_REVENUE_POOL = "<%= settings.REVENUE_POOL %>"
options.CORE_USDC = "0x4300000000000000000000000000000000000003"
options.CORE_CIRCLE_BRIDGE = "<%= settings.PLACEHOLDER_ADDRESS %>" # No CCTP on blast
options.CORE_CIRCLE_MINTER = "<%= settings.PLACEHOLDER_ADDRESS %>" # No CCTP on blast
options.CORE_DEFAULT_DESTINATION_CCTP_DOMAIN = "6"
options.CORE_WORMHOLE_CIRCLE_BRIDGE =  "<%= settings.PLACEHOLDER_ADDRESS %>" # No CCTP on blast
options.CORE_DEFAULT_DESTINATION_WORMHOLE_CHAIN_ID = "10004" # set the default domain to base for keeper bridging
# ------- Solana Vars ------- #
options.CORE_SOLANA_CCTP_DESTINATION_DOMAIN = "5"
options.CORE_SOLANA_WALLET_SEED = "<%= hexlify('wallet_authority') %>"
options.CORE_SOLANA_FIXED_PDA_SEED = "<%= hexlify('ProgramDerivedAddress') %>"
options.CORE_SOLANA_WALLET_PROGRAM_ADDRESS = "0x0dd613b80b79792f2b77dbc1bc2a88a69da961324d890ed3aa9df8d517a500b3"           #gitleaks:allow
options.CORE_SOLANA_TOKEN_MINT_ADDRESS = "0x3b442cb3912157f13a933d0134282d032b5ffecd01a2dbf1b7790608df002ea7"               #gitleaks:allow
options.CORE_SOLANA_TOKEN_PROGRAM_ADDRESS = "0x06ddf6e1d765a193d9cbe146ceeb79ac1cb485ed5f5b37913a8cf5857eff00a9"            #gitleaks:allow
options.CORE_SOLANA_ASSOCIATED_TOKEN_PROGRAM_ADDRESS = "0x8c97258f4e2489f1bb3d1029148e0d830b5a1399daff1084048e7bd8dbe9f859" #gitleaks:allow
# ---------- Wormhole Chain Ids ---------- #
options.CORE_WORMHOLE_CHAIN_ID_ARBITRUM = "10003"
options.CORE_WORMHOLE_CHAIN_ID_BASE = "10004"
options.CORE_WORMHOLE_CHAIN_ID_ETHEREUM = "10002"
options.CORE_WORMHOLE_CHAIN_ID_OPTIMISM = "10005"
options.CORE_WORMHOLE_CHAIN_ID_POLYGON = "10007"
options.CORE_WORMHOLE_CORE = "0x473e002D7add6fB67a4964F13bFd61280Ca46886"
# ---------- Circle Constants ---------- #
options.CORE_CCTP_DOMAIN_ARBITRUM = "3"
options.CORE_CCTP_DOMAIN_BASE = "6"
options.CORE_CCTP_DOMAIN_ETHEREUM = "0"
options.CORE_CCTP_DOMAIN_OPTIMISM = "2"
options.CORE_CCTP_DOMAIN_POLYGON = "7"

# ---------- Setting Post deployment parameters  ---------- #
# [invoke.setInfinexProtocolConfigBeaconFee]
# target = ["infinex.InfinexProtocolConfigBeacon"]
# func = "setWithdrawalFeeUSDC"
# args = ["<%= settings.WITHDRAWAL_FEE_USDC %>"]
# from = "<%= settings.DEPLOYER %>"
# depends = ["clone.infinex"]

[invoke.setTrustedRecoveryKeeper]
target = ["infinex.InfinexProtocolConfigBeacon"]
func = "setTrustedRecoveryKeeper"
args = ["<%= settings.TRUSTED_RECOVERY_KEEPER %>", true]
from = "<%= settings.DEPLOYER %>"
depends = ["clone.infinex"]
