name = "infinex-core-test"
version = "3.0.0"
preset = "core"
description = "Infinex Core Deployments"
#  pnpm cannon build infinex-multichain/testnets/infinex-multichain-base-sepolia.toml --chain-id 84532 --dry-run
#  CANNON_ETHERSCAN_API_URL=https://api-sepolia.basescan.org/api ./run pnpm cannon verify infinex-multichain:0.1.7@O2 --chain-id 84532 --api-key 

[var.Deploy]
DEPLOYER = "0x6298551D56F825B3b6c3350D32129Ffd3cFb198C"
REVENUE_POOL = "0x6298551D56F825B3b6c3350D32129Ffd3cFb198C"
WITHDRAWAL_FEE_USDC = "<%= parseUnits(String(0), 6) %>"
TRUSTED_RECOVERY_KEEPER =  "0x6298551D56F825B3b6c3350D32129Ffd3cFb198C"

[clone.infinex]
source = "infinex:3.0.0@core"
target = "infinex:3.0.0@core"
options.SALT = "INFINEX_0_1_7"
options.DEPLOYER = "<%= settings.DEPLOYER %>"
options.REVENUE_POOL = "<%= settings.REVENUE_POOL %>"
options.USDC = "0x036CbD53842c5426634e7929541eC2318f3dCF7e"
options.CIRCLE_BRIDGE = "0x9f3B8679c73C2Fef8b59B4f3444d4e156fb70AA5"
options.CIRCLE_MINTER = "0xE997d7d2F6E065a9A93Fa2175E878Fb9081F1f0A"
options.DEFAULT_DESTINATION_CCTP_DOMAIN = "6"
options.WORMHOLE_CIRCLE_BRIDGE = "0x2703483B1a5a7c577e8680de9Df8Be03c6f30e3c"
options.DEFAULT_DESTINATION_WORMHOLE_CHAIN_ID = "10004" # set the default domain to base for keeper bridging
# ------- Solana Vars ------- #
options.SOLANA_CCTP_DESTINATION_DOMAIN = "5"
options.SOLANA_WALLET_SEED =  "<%= hexlify('wallet_authority') %>"
options.SOLANA_FIXED_PDA_SEED = "<%= hexlify('ProgramDerivedAddress') %>"
options.SOLANA_WALLET_PROGRAM_ADDRESS = "0x0dd613b80b79792f2b77dbc1bc2a88a69da961324d890ed3aa9df8d517a500b3" #gitleaks:allow
options.SOLANA_TOKEN_MINT_ADDRESS = "0x3b442cb3912157f13a933d0134282d032b5ffecd01a2dbf1b7790608df002ea7" #gitleaks:allow
options.SOLANA_TOKEN_PROGRAM_ADDRESS = "0x06ddf6e1d765a193d9cbe146ceeb79ac1cb485ed5f5b37913a8cf5857eff00a9" #gitleaks:allow
options.SOLANA_ASSOCIATED_TOKEN_PROGRAM_ADDRESS = "0x8c97258f4e2489f1bb3d1029148e0d830b5a1399daff1084048e7bd8dbe9f859" #gitleaks:allow
# ---------- Wormhole Chain Ids ---------- #
options.WORMHOLE_CHAIN_ID_ARBITRUM = "10003"
options.WORMHOLE_CHAIN_ID_BASE = "10004"
options.WORMHOLE_CHAIN_ID_ETHEREUM = "10002"
options.WORMHOLE_CHAIN_ID_OPTIMISM = "10005"
options.WORMHOLE_CHAIN_ID_POLYGON = "10007"
options.WORMHOLE_CORE = "0x23908A62110e21C04F3A4e011d24F901F911744A"
# ---------- Circle Constants ---------- #
options.CCTP_DOMAIN_ARBITRUM = "3"
options.CCTP_DOMAIN_BASE = "6"
options.CCTP_DOMAIN_ETHEREUM = "0"
options.CCTP_DOMAIN_OPTIMISM = "2"
options.CCTP_DOMAIN_POLYGON = "7"

# ---------- Setting Post deployment parameters  ---------- #
# [invoke.setInfinexProtocolConfigBeaconFee]
# target = ["infinex.InfinexProtocolConfigBeacon"]
# func = "setWithdrawalFeeUSDC"
# args = [
#     "<%= settings.WITHDRAWAL_FEE_USDC %>",
#     ]
# from = "<%= settings.DEPLOYER %>"
# depends = ["clone.infinex"]

[invoke.setTrustedRecoveryKeeper]
target = ["infinex.InfinexProtocolConfigBeacon"]
func = "setTrustedRecoveryKeeper"
args = [
    "<%= settings.TRUSTED_RECOVERY_KEEPER %>", 
    true
    ]
from = "<%= settings.DEPLOYER %>"
depends = ["clone.infinex"]
