name = "infinex-multichain"
version = "1.0.0"
preset = "apps"
description = "Infinex App integrations"
#    pnpm cannon build infinex-multichain/testnets/infinex-multichain-apps-arbitrum-sepolia.toml --chain-id 421614 --private-key 

[var.Deploy]
DEPLOYER = "0xBF32844C0edF6Ab3f6565a5dfF1D7B30CE4ec01F"
REVENUE_POOL = "0xBF32844C0edF6Ab3f6565a5dfF1D7B30CE4ec01F"
MULTI_SIG = "0xBF32844C0edF6Ab3f6565a5dfF1D7B30CE4ec01F"

[clone.infinex]
options.APPS_DEPLOYER = "<%= settings.DEPLOYER %>"
# Curve Stableswap Config
options.CRV_DEPLOYER = "<%= settings.DEPLOYER %>"
options.APPS_USDC = "0x1c7D4B196Cb0C7B01d743Fbc6116a902379C7238"
options.APPS_CRV_CURVE_STABLESWAP_FACTORY = "<%= keccak256('0x12341234').slice(0,42) %>" 
source = "infinex:1.0.0@apps"
target = "infinex:1.0.0@apps"

