#  pnpm cannon build infinex-multichain/testnets/infinex-curve-app-test.sepolia.toml --chain-id 11155111 --dry-run --upgrade-from
#  pnpm cannon publish infinex-curve-app-test:1.1.0@curve-stableswap --chain-id 11155111 --exclude-cloned
#  CANNON_ETHERSCAN_API_URL=https://api-sepolia.etherscan.io/api pnpm cannon verify infinex-curve-app-test:latest@curve-stableswap --chain-id 11155111 --api-key

name = "infinex-curve-app-test"
version = "1.1.0"
preset = "curve-stableswap"
description = "Infinex App integration for Curve StableSwap"

[var.Deploy]
DEPLOYER = "0x6298551D56F825B3b6c3350D32129Ffd3cFb198C"

[clone.CurveStableSwap]
options.CURVE_STABLESWAP_SALT = "CURVE_STABLESWAP_1_1_0"
options.CURVE_STABLESWAP_OWNER = "<%= settings.DEPLOYER %>"
options.CURVE_STABLESWAP_USDC = "0x1c7D4B196Cb0C7B01d743Fbc6116a902379C7238"
options.CURVE_STABLESWAP_FACTORY = "0xfb37b8D939FFa77114005e61CFc2e543d6F49A81" 
source = "infinex:1.1.0@curve-stableswap"
target = "infinex:1.1.0@curve-stableswap"

# ---------- Add Supported Pools To App Beacon ---------- #
[var.SupportedPools]
FAKE_USDCUSDE_POOL = "0xeef7894341be733c8d8805c54c369e1297e3c86e"
FAKE_USDCUSDE_POOL_2 = "0xf937a1e8f0d6b1b5133351a28ca42bba3d56bfa4"

[invoke.AddUSDCUSDEPool]
target = ["CurveStableSwap.CurveStableSwapAppBeacon"]
func = "setIsSupportedPool"
args = [
    "<%= settings.FAKE_USDCUSDE_POOL %>",
    true,
]
fromCall.func = "owner"

[invoke.AddUSDCUSDEPool2]
target = ["CurveStableSwap.CurveStableSwapAppBeacon"]
func = "setIsSupportedPool"
args = [
    "<%= settings.FAKE_USDCUSDE_POOL_2 %>",
    true,
]
fromCall.func = "owner"