name = "infinex-core-test"
version = "3.0.2"
preset = "core"
description = "Infinex Core Deployments"
#  pnpm cannon build infinex-multichain/testnets/infinex-multichain-arbitrum-sepolia.toml --chain-id 421614 --dry-run --upgrade-from 
#  pnpm cannon publish infinex-core-test:latest@core --chain-id 421614 --exclude-cloned
#  CANNON_ETHERSCAN_API_URL=https://api-sepolia.arbiscan.io/api pnpm cannon verify infinex-core-test:latest@core --chain-id 421614 --api-key 

[var.Deploy]
DEPLOYER = "0x6298551D56F825B3b6c3350D32129Ffd3cFb198C"
REVENUE_POOL = "0x6298551D56F825B3b6c3350D32129Ffd3cFb198C"
WITHDRAWAL_FEE_USDC = "<%= parseUnits(String(0), 6) %>"
TRUSTED_RECOVERY_KEEPER = "0x996c7B455C9A9449A612b5B66Cc1dd24b81DB3fb"

[pull.v1]
source = "infinex-multichain:0.1.7@O2"

[clone.infinex]
source = "infinex:3.0.0@core"
target = "infinex:3.0.0@core"
options.CORE_SALT = "INFINEX_0_1_7"
options.CORE_DEPLOYER = "<%= settings.DEPLOYER %>"
options.CORE_INITIAL_PROXY_IMPLEMENTATION = "<%= imports.v1.imports.infinex.contracts.InitialProxyImplementation.address %>"
options.CORE_REVENUE_POOL = "<%= settings.REVENUE_POOL %>"
options.CORE_USDC = "0x75faf114eafb1BDbe2F0316DF893fd58CE46AA4d"
options.CORE_CIRCLE_BRIDGE = "0x9f3B8679c73C2Fef8b59B4f3444d4e156fb70AA5"
options.CORE_CIRCLE_MINTER = "0xE997d7d2F6E065a9A93Fa2175E878Fb9081F1f0A"
options.CORE_DEFAULT_DESTINATION_CCTP_DOMAIN = "6"
options.CORE_WORMHOLE_CIRCLE_BRIDGE = "0x2703483B1a5a7c577e8680de9Df8Be03c6f30e3c"
options.CORE_DEFAULT_DESTINATION_WORMHOLE_CHAIN_ID = "10004"                       # set the default domain to base for keeper bridging
# ------- Solana Vars ------- #
options.CORE_SOLANA_CCTP_DESTINATION_DOMAIN = "5"
options.CORE_SOLANA_WALLET_SEED = "<%= hexlify('wallet_authority') %>"
options.CORE_SOLANA_FIXED_PDA_SEED = "<%= hexlify('ProgramDerivedAddress') %>"
options.CORE_SOLANA_WALLET_PROGRAM_ADDRESS = "0x0dd613b80b79792f2b77dbc1bc2a88a69da961324d890ed3aa9df8d517a500b3"           #gitleaks:allow
options.CORE_SOLANA_TOKEN_MINT_ADDRESS = "0x3b442cb3912157f13a933d0134282d032b5ffecd01a2dbf1b7790608df002ea7"               #gitleaks:allow
options.CORE_SOLANA_TOKEN_PROGRAM_ADDRESS = "0x06ddf6e1d765a193d9cbe146ceeb79ac1cb485ed5f5b37913a8cf5857eff00a9"            #gitleaks:allow
options.CORE_SOLANA_ASSOCIATED_TOKEN_PROGRAM_ADDRESS = "0x8c97258f4e2489f1bb3d1029148e0d830b5a1399daff1084048e7bd8dbe9f859" #gitleaks:allow
# ---------- Wormhole Chain Ids ---------- #
options.CORE_WORMHOLE_CHAIN_ID_ARBITRUM = "10003"
options.CORE_WORMHOLE_CHAIN_ID_BASE = "10004"
options.CORE_WORMHOLE_CHAIN_ID_ETHEREUM = "10002"
options.CORE_WORMHOLE_CHAIN_ID_OPTIMISM = "10005"
options.CORE_WORMHOLE_CHAIN_ID_POLYGON = "10007"
options.CORE_WORMHOLE_CORE = "0x6b9C8671cdDC8dEab9c719bB87cBd3e782bA6a35"
# ---------- Circle Constants ---------- #
options.CORE_CCTP_DOMAIN_ARBITRUM = "3"
options.CORE_CCTP_DOMAIN_BASE = "6"
options.CORE_CCTP_DOMAIN_ETHEREUM = "0"
options.CORE_CCTP_DOMAIN_OPTIMISM = "2"
options.CORE_CCTP_DOMAIN_POLYGON = "7"

# ---------- Setting Post deployment parameters  ---------- #
# [invoke.setInfinexProtocolConfigBeaconFee]
# target = ["infinex.InfinexProtocolConfigBeacon"]
# func = "setWithdrawalFeeUSDC"
# args = ["<%= settings.WITHDRAWAL_FEE_USDC %>"]
# from = "<%= settings.DEPLOYER %>"
# depends = ["clone.infinex"]

[invoke.setTrustedRecoveryKeeper]
target = ["infinex.InfinexProtocolConfigBeacon"]
func = "setTrustedRecoveryKeeper"
args = ["<%= settings.TRUSTED_RECOVERY_KEEPER %>", true]
from = "<%= settings.DEPLOYER %>"
depends = ["clone.infinex"]
