name = "infinex-multichain"
version = "1.0.0"
preset = "apps"
description = "Infinex App integrations"
#   pnpm cannon build infinex-multichain/mainnets/infinex-multichain-apps-polygon.toml --chain-id 137 --private-key  
#   CANNON_ETHERSCAN_API_URL=https://api-amoy.polygonscan.com/api   ./run pnpm cannon verify infinex-multichain:0.1.7@apps --chain-id 137 --api-key

[var.Deploy]
DEPLOYER = "0x7Bb5DfC8622D296bF259c951490dC9E1Cc0951d3"
MULTI_SIG = "0x87213Fa8BA3b8170E940aAF47096A4322a344De3"

[clone.infinexApps]
options.APPS_DEPLOYER = "<%= settings.DEPLOYER %>"
# Curve Stableswap Config
options.CRV_DEPLOYER = "<%= settings.DEPLOYER %>"
options.APPS_USDC = "0x3c499c542cef5e3811e1192ce70d8cc03d5c3359"
options.APPS_CRV_CURVE_STABLESWAP_FACTORY = "0x1764ee18e8B3ccA4787249Ceb249356192594585" 
source = "infinex:1.0.0@apps"
target = "infinex:1.0.0@apps"

# invoke the transfer of ownership from the deployer to the multisig

[invoke.transferOwnershipAppRegistry]
target = ["infinexApps.AppRegistry"]
func = "transferOwnership"
args = ["<%= settings.MULTI_SIG %>"]
from = "<%= settings.DEPLOYER %>"

[invoke.transferOwnershipCurveStableSwapAppBeacon]
target = ["infinexApps.CRV.CurveStableSwapAppBeacon"]
func = "transferOwnership"
args = ["<%= settings.MULTI_SIG %>"]
from = "<%= settings.DEPLOYER %>"

# # # # invoke the acceptance of the ownership transfer from the multisig

# [invoke.acceptOwnershipCRVBeacon]
# target = ["infinexApps.CRV.CurveStableSwapAppBeacon"]
# func = "acceptOwnership"
# from = "<%= settings.MULTI_SIG %>"
# depends = ["invoke.transferOwnershipCurveStableSwapAppBeacon"]

# [invoke.acceptOwnershipAppRegistry]
# target = ["infinexApps.AppRegistry"]
# func = "acceptOwnership"
# from = "<%= settings.MULTI_SIG %>"
# depends = ["invoke.transferOwnershipAppRegistry"]