name = "infinex-multichain"
version = "1.0.0"
preset = "O2"
description = "Infinex MultiChain Deployments"
# --chain-id 137

[var.deploy]
DEPLOYER = "0x3F768E3aC5eE75A2F39CFD7d72Eb3a40Bddb5ecB"
REVENUE_POOL = "0x33FaF56Cb2c854231bdA8De328bbAddcF76D9836"
MULTI_SIG = "0x5A2B4096754Bd094C40A0e89BC7E017fE38e300c"
WITHDRAWAL_FEE_USDC = "<%= parseUnits(String(1), 6) %>"

[clone.infinex]
options.SALT = "INFINEX_1_0_0"
options.DEPLOYER = "<%= settings.DEPLOYER %>"
options.REVENUE_POOL = "<%= settings.REVENUE_POOL %>"
options.MINIMUM_BRIDGE_AMOUNT =  "<%= parseUnits(String(1), 6) %>"
options.USDC = "0x3c499c542cef5e3811e1192ce70d8cc03d5c3359"
options.CIRCLE_BRIDGE = "0x9daF8c91AEFAE50b9c0E69629D3F6Ca40cA3B3FE"
options.CIRCLE_MINTER = "0x10f7835F827D6Cf035115E10c50A853d7FB2D2EC"
options.DEFAULT_DESTINATION_CCTP_DOMAIN = "6"
options.WORMHOLE_CIRCLE_BRIDGE = "0x2703483B1a5a7c577e8680de9Df8Be03c6f30e3c"
options.DEFAULT_DESTINATION_WORMHOLE_CHAIN_ID = "30" # set the default domain to base for keeper bridging

# ------- Solana Vars ------- #
options.SOLANA_CCTP_DESTINATION_DOMAIN = "5"
options.SOLANA_WALLET_SEED =  "<%= hexlify('wallet_authority') %>"
options.SOLANA_FIXED_PDA_SEED = "<%= hexlify('ProgramDerivedAddress') %>"
options.SOLANA_WALLET_PROGRAM_ADDRESS = "0x0aacda33cf045c0dd658e67c577bade83951034129e2201bb7dfd6372c6e9e64" #gitleaks:allow
options.SOLANA_TOKEN_MINT_ADDRESS = "0xc6fa7af3bedbad3a3d65f36aabc97431b1bbe4c2d2f6e0e47ca60203452f5d61" #gitleaks:allow
options.SOLANA_TOKEN_PROGRAM_ADDRESS = "0x06ddf6e1d765a193d9cbe146ceeb79ac1cb485ed5f5b37913a8cf5857eff00a9" #gitleaks:allow
options.SOLANA_ASSOCIATED_TOKEN_PROGRAM_ADDRESS = "0x8c97258f4e2489f1bb3d1029148e0d830b5a1399daff1084048e7bd8dbe9f859" #gitleaks:allow

# ---------- Wormhole Chain Ids ---------- #
options.WORMHOLE_CHAIN_ID_ARBITRUM = "23"
options.WORMHOLE_CHAIN_ID_BASE = "30"
options.WORMHOLE_CHAIN_ID_ETHEREUM = "2"
options.WORMHOLE_CHAIN_ID_OPTIMISM = "24"
options.WORMHOLE_CHAIN_ID_POLYGON = "5"
source = "infinex:1.0.0@O2"

# ---------- Setting Post deployment parameters  ---------- #
[invoke.setInfinexProtocolConfigBeaconFee]
target = ["infinex.InfinexProtocolConfigBeacon"]
func = "setWithdrawalFeeUSDC"
args = [
    "<%= settings.WITHDRAWAL_FEE_USDC %>",
    ]
from = "<%= settings.DEPLOYER %>"
depends = ["clone.infinex"]

[invoke.AccountFactoryInitialize]
target = ["infinex.AccountFactory"]
func = "initialize"
args = [
    "<%= imports.infinex.contracts.InfinexProtocolConfigBeacon.address %>"
]
from = "<%= settings.DEPLOYER %>"
depends = ["clone.infinex"]
