name = "infinex-multichain"
version = "1.0.0"
preset = "apps"
description = "Infinex App integrations"
#   pnpm cannon build infinex-multichain/mainnets/infinex-multichain-apps-optimism.toml --chain-id 10 --private-key 

[var.Deploy]
DEPLOYER = "0x7Bb5DfC8622D296bF259c951490dC9E1Cc0951d3"
MULTI_SIG = "0x7299aF061A210157f7AcaEaDa22534ae3b72C956"

[clone.infinexApps]
options.APPS_DEPLOYER = "<%= settings.DEPLOYER %>"
options.APPS_USDC = "0x0b2c639c533813f4aa9d7837caf62653d097ff85"
# Curve Stableswap Config
options.APPS_CRV_CURVE_STABLESWAP_FACTORY = "0x5eeE3091f747E60a045a2E715a4c71e600e31F6E" 
source = "infinex:1.0.0@apps"
target = "infinex:1.0.0@apps"

# invoke the transfer of ownership from the deployer to the multisig

[invoke.transferOwnershipAppRegistry]
target = ["infinexApps.AppRegistry"]
func = "transferOwnership"
args = ["<%= settings.MULTI_SIG %>"]
from = "<%= settings.DEPLOYER %>"

[invoke.transferOwnershipCurveStableSwapAppBeacon]
target = ["infinexApps.CRV.CurveStableSwapAppBeacon"]
func = "transferOwnership"
args = ["<%= settings.MULTI_SIG %>"]
from = "<%= settings.DEPLOYER %>"

# # # # invoke the acceptance of the ownership transfer from the multisig

# [invoke.acceptOwnershipCRVBeacon]
# target = ["infinexApps.CRV.CurveStableSwapAppBeacon"]
# func = "acceptOwnership"
# from = "<%= settings.MULTI_SIG %>"
# depends = ["invoke.transferOwnershipCurveStableSwapAppBeacon"]

# [invoke.acceptOwnershipAppRegistry]
# target = ["infinexApps.AppRegistry"]
# func = "acceptOwnership"
# from = "<%= settings.MULTI_SIG %>"
# depends = ["invoke.transferOwnershipAppRegistry"]