#  pnpm cannon build infinex-multichain/mainnets/infinex-curve-app.optimism.toml --chain-id 10 --dry-run
#  pnpm cannon publish infinex-curve-app:1.1.0@curve-stableswap --chain-id 10 --exclude-cloned
#  pnpm cannon verify infinex-curve-app:latest@curve-stableswap --chain-id 10 --api-key

name = "infinex-curve-app"
version = "1.1.0"
preset = "curve-stableswap"
description = "Infinex App integration for Curve StableSwap"

[var.Deploy]
DEPLOYER = "0x6298551D56F825B3b6c3350D32129Ffd3cFb198C"
MULTISIG = "0x7299aF061A210157f7AcaEaDa22534ae3b72C956"

[clone.CurveStableSwap]
source = "infinex:1.1.0@curve-stableswap"
target = "infinex:1.1.0@curve-stableswap"
options.CURVE_STABLESWAP_SALT = "CURVE_STABLESWAP_1_1_0"
options.CURVE_STABLESWAP_OWNER = "<%= settings.DEPLOYER %>"
options.CURVE_STABLESWAP_USDC = "0x0b2c639c533813f4aa9d7837caf62653d097ff85"
options.CURVE_STABLESWAP_FACTORY = "0x5eeE3091f747E60a045a2E715a4c71e600e31F6E"

# ---------- Transfer Ownership ---------- #

[invoke.TransferOwnershipNewBeacon]
target = ["CurveStableSwap.CurveStableSwapAppBeacon"]
func = "transferOwnership"
args = ["<%= settings.MULTISIG %>"]
fromCall.func = "owner"
