name = "infinex-multichain"
version = "1.0.0"
preset = "apps"
description = "Infinex App integrations"
#  pnpm cannon build infinex-multichain/mainnets/infinex-multichain-apps-ethereum.toml --chain-id 1 --private-key
#   CANNON_ETHERSCAN_API_URL=https://api.etherscan.io/api ./run pnpm cannon verify infinex-multichain:0.1.7@apps --chain-id 1  --api-key

[var.Deploy]
DEPLOYER = "0x7Bb5DfC8622D296bF259c951490dC9E1Cc0951d3"
MULTI_SIG = "0x1548c73d55e3D3000B5351852790B05fC67d2B28"

[clone.infinexApps]
options.APPS_DEPLOYER = "<%= settings.DEPLOYER %>"
options.APPS_USDC = "0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48"
# Curve Stableswap Config
options.APPS_CRV_CURVE_STABLESWAP_FACTORY = "0x6A8cbed756804B16E05E741eDaBd5cB544AE21bf" 
source = "infinex:1.0.0@apps"
target = "infinex:1.0.0@apps"

# invoke the transfer of ownership from the deployer to the multisig

[invoke.transferOwnershipAppRegistry]
target = ["infinexApps.AppRegistry"]
func = "transferOwnership"
args = ["<%= settings.MULTI_SIG %>"]
from = "<%= settings.DEPLOYER %>"

[invoke.transferOwnershipCurveStableSwapAppBeacon]
target = ["infinexApps.CRV.CurveStableSwapAppBeacon"]
func = "transferOwnership"
args = ["<%= settings.MULTI_SIG %>"]
from = "<%= settings.DEPLOYER %>"

# # # # invoke the acceptance of the ownership transfer from the multisig

# [invoke.acceptOwnershipCRVBeacon]
# target = ["infinexApps.CRV.CurveStableSwapAppBeacon"]
# func = "acceptOwnership"
# from = "<%= settings.MULTI_SIG %>"
# depends = ["invoke.transferOwnershipCurveStableSwapAppBeacon"]

# [invoke.acceptOwnershipAppRegistry]
# target = ["infinexApps.AppRegistry"]
# func = "acceptOwnership"
# from = "<%= settings.MULTI_SIG %>"
# depends = ["invoke.transferOwnershipAppRegistry"]