# Migrate the testnet account factory and beacon to use the new versions
# pnpm cannon build scripts/migration/testnets/4-update-to-latest-beacons.toml --dry-run --chain-id 

name = "infinex-core-test-factory-migration"
version = "3.0.0"

[pull.latestVersion]
source = "infinex-core-test:latest@core"

[pull.v1]
source = "infinex-multichain:1.0.0@O2"

# ---------- Update Factory ---------- #

[invoke.AccountFactoryUpdateInfinexProtocolConfigBeacon]
target = ["v1.infinex.AccountFactory"]
func = "updateInfinexProtocolConfigBeacon"
args = [
    "<%= imports.latestVersion.imports.infinex.contracts.InfinexProtocolConfigBeacon.address %>",
]
fromCall.func = "owner"
depends = [
    "invoke.v2BeaconSetLatestInfinexProtocolConfigBeacon",
    "invoke.priorDeploymentBeaconSetLatestInfinexProtocolConfigBeacon",
] # change this to the current beacon the factory is pointing to
