# Migrate the testnet account factory and beacon to use the new versions
# pnpm cannon build scripts/migration/staging/4-update-factory.toml --dry-run --chain-id 

name = "infinex-core-test-factory"
version = "3.0.0"

[pull.latestVersion]
source = "infinex-core-test:latest@core"

[pull.AccountFactory]
source = "infinex-account-factory-test:1.0.0@main"

# ---------- Update Factory ---------- #

[invoke.AccountFactoryUpdateInfinexProtocolConfigBeacon]
target = ["AccountFactory.AccountFactory.AccountFactory"]
func = "updateInfinexProtocolConfigBeacon"
args = [
    "<%= imports.latestVersion.imports.infinex.contracts.InfinexProtocolConfigBeacon.address %>",
]
fromCall.func = "owner"
