name = "infinex-multichain"
preset = "craterun"
version = "1.0.0"
description = "Smart Contracts used for the Infinex Craterun Campaign"

# --chain-id 84532

[var.Deploy]
CRATERUN_DEPLOYER = "0x3F768E3aC5eE75A2F39CFD7d72Eb3a40Bddb5ecB"
CRATERUN_KEEPER= "0x3F768E3aC5eE75A2F39CFD7d72Eb3a40Bddb5ecB"
CRATE_POINTS_NAME = "InfinexCratePoints"

[pull.InfinexMultichain]
source = "infinex-multichain:0.1.7@O2"

[clone.InfinexCraterun]
options.DEPLOYER = "<%= settings.CRATERUN_DEPLOYER %>"
options.ENTROPY_ = "0x41c9e39574F40Ad34c79f1C99B66A45eFB830d4c"         # Pyth Entropy contract address
options.ENTROPY_PROVIDER = "0x6CC14824Ea2918f5De5C2f75A9Da968ad4BD6344" # Pyth Entropy provider address
options.FORWARDER= "<%= imports.InfinexMultichain.imports.infinex.contracts.Forwarder.address %>"         # Forwarder contract address
options.ACCOUNT_FACTORY = "<%= imports.InfinexMultichain.imports.infinex.contracts.AccountFactory.address %>" # AccountFactory contract address
options.CRATE_POINTS_NAME = "<%= settings.CRATE_POINTS_NAME %>"
options.TOTAL_CRATES = "5000000" # 5 million
options.REWARDS_DURATION = "604800" # 1 week
source = "infinex:1.0.0@craterun"
target = "infinex:1.0.0@craterun"
tags=["1.0.0"]

# ---------- Settings post deployment parameters  ---------- #

# ---------- Initializers ---------- #

[invoke.CratePointsInitialize]
target = ["InfinexCraterun.CratePointsProxy"]
func = "initialize"
args = ["<%= settings.CRATERUN_DEPLOYER %>", "<%= settings.CRATE_POINTS_NAME %>"]

# ---------- CratePoints Minters ---------- #

[invoke.CratePointsSetMinterForDeployer]
target=["InfinexCraterun.CratePointsProxy"]
func="setAuthorizedMinter"
args=["<%= settings.CRATERUN_DEPLOYER  %>", true]
from = "<%= settings.CRATERUN_DEPLOYER %>"

[invoke.CratePointsSetMinterForCrateOpener]
target=["InfinexCraterun.CratePointsProxy"]
func="setAuthorizedMinter"
args=["<%= imports.InfinexCraterun.contracts.CrateOpener.address  %>", true]
from = "<%= settings.CRATERUN_DEPLOYER %>"

[invoke.CratePointsSetMinterForStakingRewards]
target=["InfinexCraterun.CratePointsProxy"]
func="setAuthorizedMinter"
args=["<%= imports.InfinexCraterun.contracts.CtPStakingRewards.address  %>", true]
from = "<%= settings.CRATERUN_DEPLOYER %>"

# ---------- Keepers ---------- #

[invoke.CrateOpenerSetKeeper]
target=["InfinexCraterun.CrateOpener"]
func="setAuthorizedKeeper"
args=["<%= settings.CRATERUN_KEEPER  %>", true]
from = "<%= settings.CRATERUN_DEPLOYER %>"

[invoke.StakingRewardsSetKeeper]
target=["InfinexCraterun.CtPStakingRewards"]
func="setAuthorizedKeeper"
args=["<%= settings.CRATERUN_KEEPER  %>", true]
from = "<%= settings.CRATERUN_DEPLOYER %>"




