name = "infinex-gp"
version = "0.1.5"
preset = "StW"
description = "Infinex Governance Points Deployments"

# --chain-id 84532

[var.Deploy]
GP_DEPLOYER = "0x3F768E3aC5eE75A2F39CFD7d72Eb3a40Bddb5ecB"
GP_MULTI_SIG = "0x3F768E3aC5eE75A2F39CFD7d72Eb3a40Bddb5ecB"
GP_TRUSTED_KEEPER = "0x3F768E3aC5eE75A2F39CFD7d72Eb3a40Bddb5ecB"
STWPOINTS = "<%= parseEther('33000000') %>"
SOLANA_MULTIPLIER = "<%= parseEther('1') %>"

[pull.InfinexMultichain]
source = "infinex-multichain:0.1.5@O2"

[clone.InfinexGovernancePoints]
options.GP_SALT = "GP_0_1_5"
options.GP_DEPLOYER = "<%= settings.GP_DEPLOYER %>"
options.ACCOUNT_FACTORY = "<%= imports.InfinexMultichain.imports.infinex.contracts.AccountFactory.address %>"
options.FORWARDER = "<%= imports.InfinexMultichain.imports.infinex.contracts.Forwarder.address %>"
options.INX_USDC = "<%= imports.InfinexMultichain.imports.infinex.settings.USDC %>"
options.REWARDS_DURATION =  "2419200"
source = "infinex-governance-points:0.1.5@stw"
depends = ["pull.InfinexMultichain"]

# ---------- Initialise GP Contracts  ---------- #

# [invoke.upgrade]
# target = ["InfinexGovernancePoints.GovernancePointsInitialProxy"]
# func = "upgradeTo"
# args = ["<%= imports.InfinexGovernancePoints.contracts.GovernancePointsImplementation.address %>"]
# depends = ["provision.InfinexGovernancePoints"]
# factory.CoreProxy.abiOf = ["InfinexGovernancePoints.GovernancePointsImplementation"]
# factory.CoreProxy.event = "Upgraded"
# factory.CoreProxy.arg = 0
# factory.CoreProxy.highlight = true

[invoke.GovernancePointsProxyInitialize]
target = ["InfinexGovernancePoints.GovernancePointsProxy"]
func = "initialize"
args = ["<%= settings.GP_DEPLOYER %>"]
depends = ["clone.InfinexGovernancePoints"]

# ---------- Setting Post deployment parameters  ---------- #

[invoke.attachSTWCampaign]
target = ["InfinexGovernancePoints.GovernancePointsProxy"]
func = "addAuthorisedMinter"
args = [ "<%= imports.InfinexGovernancePoints.contracts.StWStakingRewards.address %>" ]
from = "<%= settings.GP_DEPLOYER %>"
depends = ["invoke.GovernancePointsProxyInitialize"]

[invoke.setSolanaMultiplier]
target = ["InfinexGovernancePoints.StWStakingRewards"]
func = "setSolanaMultiplier"
args = [ "<%= settings.SOLANA_MULTIPLIER %>" ]
from = "<%= settings.GP_DEPLOYER %>"
depends = ["clone.InfinexGovernancePoints"]

[invoke.setAuthorizedKeeper]
target = ["InfinexGovernancePoints.StWStakingRewards"]
func = "setAuthorizedKeeper"
args = [ "<%= settings.GP_TRUSTED_KEEPER %>" , true]
from = "<%= settings.GP_DEPLOYER %>"
depends = ["clone.InfinexGovernancePoints"]

[invoke.StWStakingRewardsNotifyRewardAmount]
target = ["InfinexGovernancePoints.StWStakingRewards"]
func = "notifyRewardAmount"
args = [ "<%= settings.STWPOINTS %>" ]
from = "<%= settings.GP_DEPLOYER %>"
depends = ["invoke.attachSTWCampaign"]

