#  pnpm cannon build infinex-omnibus/mainnets/infinex-omnibus.blast.toml --chain-id 81457 --dry-run
#  pnpm cannon publish infinex-omnibus:3.0.0@omnibus --chain-id 81457 --exclude-cloned

name = "infinex-omnibus"
version = "3.0.0"
preset = "omnibus"
description = "All Infinex Deployments"

[pull.AccountFactoryV1]
source = "infinex-account-factory:1.0.0@main"

[pull.CoreV3]
source = "infinex-core:3.0.0@core"

[pull.CardRun]
source = "infinex-cardrun:1.0.0@cardrun"