# Transfer ownership of the contracts to the multisig from the deployer

# pnpm cannon build scripts/migration/prod/patron/1-accept-ownership/1-accept-ownership.polygon.toml --dry-run --chain-id 137

name = "infinex-transfer-ownership"
version = "1.0.0"

[var.MultiSigs]
MULTISIG_0 = "0x5a21D5738514CA16995F63E9E4eb1d7e8364658c"

[pull.InfinexPatronPurchase]
source = "infinex-patron:1.0.0@patron-purchase"

# Accept Ownership

[invoke.acceptOwnershipPatronPurchaseAppBeacon]
target = ["InfinexPatronPurchase.infinexPatronPurchase.PatronPurchaseAppBeacon"]
func = "acceptOwnership"
from = "<%= settings.MULTISIG_0 %>"

[invoke.acceptOwnershipPatronPointOfPurchase]
target = ["InfinexPatronPurchase.infinexPatronPurchase.PatronPointOfPurchase"]
func = "acceptOwnership"
from = "<%= settings.MULTISIG_0 %>"

