# pnpm cannon build infinex-patron/vesting/1-patron-vesting-configuration.ethereum.toml --dry-run --chain-id 1

name = "infinex-patron-vesting-configuration"
preset = "config"
version = "1.0.1"
description = "Configuration for the Infinex Patron Vesting"

[pull.InfinexPatronDistributor]
source = "infinex-patron-vesting:1.0.1@patron-vesting"

[invoke.SetTier1StartTime]
target = ["<%= imports.InfinexPatronVesting.imports.InfinexPatronVesting.contracts.PatronVesting.address %>"]
func = "setTierStartTime"
args = [1, 0] # 
fromCall.func = "owner"

[invoke.SetTier2StartTime]
target = ["<%= imports.InfinexPatronVesting.imports.InfinexPatronVesting.contracts.PatronVesting.address %>"]
func = "setTierStartTime"
args = [2, 0] # 
fromCall.func = "owner"

[invoke.SetTier3StartTime]
target = ["<%= imports.InfinexPatronVesting.imports.InfinexPatronVesting.contracts.PatronVesting.address %>"]
func = "setTierStartTime"
args = [3, 0] # 
fromCall.func = "owner"

[invoke.SetTier4StartTime]
target = ["<%= imports.InfinexPatronVesting.imports.InfinexPatronVesting.contracts.PatronVesting.address %>"]
func = "setTierStartTime"
args = [4, 0] # 
fromCall.func = "owner"

[invoke.SetTier5StartTime]
target = ["<%= imports.InfinexPatronVesting.imports.InfinexPatronVesting.contracts.PatronVesting.address %>"]
func = "setTierStartTime"
args = [5, 0] # 
fromCall.func = "owner"

[invoke.addTier6]
target = ["InfinexPatronVesting.PatronVesting"]
func = "setTierStartTime"
args = [6, 0] # 
fromCall.func = "owner"
