# Migrate the testnet account factory and beacon to use the new versions

[pull.latestVersion]
source = "infinex-multichain:3.0.0@core"

[pull.v2]
source = "infinex-multichain:1.1.0@O2"

[pull.v1]
source = "infinex-multichain:0.1.7@O2"

[invoke.v1BeaconSetLatestInfinexProtocolConfigBeacon]
target = ["v1.infinex.InfinexProtocolConfigBeacon"]
func = "setLatestInfinexProtocolConfigBeacon"
args = ["<%= latestVersion.infinex.contracts.InfinexProtocolConfigBeacon.address %>"]
fromCall.func = "owner"

[invoke.v2BeaconSetLatestInfinexProtocolConfigBeacon]
target = ["v2.infinex.InfinexProtocolConfigBeacon"]
func = "setLatestInfinexProtocolConfigBeacon"
args = ["<%= latestVersion.infinex.contracts.InfinexProtocolConfigBeacon.address %>"]
fromCall.func = "owner"

[invoke.AccountFactoryUpdateInfinexProtocolConfigBeacon]
target = ["originalVersion.infinex.AccountFactory"]
func = "updateInfinexProtocolConfigBeacon"
args = ["<%= latestVersion.infinex.contracts.InfinexProtocolConfigBeacon.address %>"]
fromCall.func = "owner"
depends = ["invoke.OldBeaconSetLatestInfinexProtocolConfigBeacon"]
