# Migrate the testnet account factory and beacon to use the new versions
# pnpm cannon build scripts/migration/testnets/update-beacons-latest.toml --dry-run --chain-id  

name = "infinex-core-test-migration"
version = "3.0.1"

[pull.latestVersion]
source = "infinex-core-test:latest@core"

[pull.priorDeployment]
source = "infinex-core-test:3.0.0@core"

[pull.v2]
source = "infinex-multichain:1.1.0@O2"

[pull.v1]
source = "infinex-multichain:0.1.7@O2"

# ---------- Update Old Beacons ---------- #

[invoke.v1BeaconSetLatestInfinexProtocolConfigBeacon]
target = ["v1.infinex.InfinexProtocolConfigBeacon"]
func = "setLatestInfinexProtocolConfigBeacon"
args = [
    "<%= imports.latestVersion.imports.infinex.contracts.InfinexProtocolConfigBeacon.address %>",
]
fromCall.func = "owner"

[invoke.v2BeaconSetLatestInfinexProtocolConfigBeacon]
target = ["v2.infinex.InfinexProtocolConfigBeacon"]
func = "setLatestInfinexProtocolConfigBeacon"
args = [
    "<%= imports.latestVersion.imports.infinex.contracts.InfinexProtocolConfigBeacon.address %>",
]
fromCall.func = "owner"

[invoke.priorDeploymentBeaconSetLatestInfinexProtocolConfigBeacon]
target = ["priorDeployment.infinex.InfinexProtocolConfigBeacon"]
func = "setLatestInfinexProtocolConfigBeacon"
args = [
    "<%= imports.latestVersion.imports.infinex.contracts.InfinexProtocolConfigBeacon.address %>",
]
fromCall.func = "owner"

# ---------- Update Factory ---------- #

[invoke.AccountFactoryUpdateInfinexProtocolConfigBeacon]
target = ["v1.infinex.AccountFactory"]
func = "updateInfinexProtocolConfigBeacon"
args = [
    "<%= imports.latestVersion.imports.infinex.contracts.InfinexProtocolConfigBeacon.address %>",
]
fromCall.func = "owner"
depends = [
    "invoke.v2BeaconSetLatestInfinexProtocolConfigBeacon",
    "invoke.priorDeploymentBeaconSetLatestInfinexProtocolConfigBeacon",
] # change this to the current beacon the factory is pointing to
