# Migrate the testnet account factory and beacon to use the new versions
# pnpm cannon build scripts/migration/prod/1-update-to-latest-beacons.toml --dry-run --chain-id 
# ./cannon_chains.sh "pnpm cannon build scripts/migration/prod/1-update-to-latest-beacons.toml --chain-id CHAIN_ID --dry-run" -e mainnets

name = "infinex-core-beacon-update"
version = "3.0.0"

[pull.latestVersion]
source = "infinex-core:latest@core"

[pull.v1]
source = "infinex-multichain:1.0.0@O2"

# ---------- Update Old Beacons ---------- #

[invoke.v1BeaconSetLatestInfinexProtocolConfigBeacon]
target = ["v1.infinex.InfinexProtocolConfigBeacon"]
func = "setLatestInfinexProtocolConfigBeacon"
args = [
    "<%= imports.latestVersion.imports.infinex.contracts.InfinexProtocolConfigBeacon.address %>",
]
fromCall.func = "owner"
