name = "infinex-gp"
version = "2.0.0staging"
preset = "StW"
description = "Infinex Governance Points Deployments"

#  ./run pnpm cannon build infinex-governance-points/staging/infinex-governance-points-base.toml --chain-id 8453 --private-key 
#   CANNON_ETHERSCAN_API_URL=https://api.basescan.org/api ./run pnpm cannon verify infinex-gp:[version]g@StW --chain-id 8453 --api-key


[var.Deploy]
GP_DEPLOYER = "0x6298551D56F825B3b6c3350D32129Ffd3cFb198C"
GP_MULTI_SIG = "0x715453251C2FA71cbA3F9159e4862D01D016b579"
GP_TRUSTED_KEEPER = "0x6298551D56F825B3b6c3350D32129Ffd3cFb198C"
STWPOINTS = "<%= parseEther('33000000') %>"
SOLANA_MULTIPLIER = "<%= parseEther('1') %>"

[pull.InfinexMultichain]
source = "infinex-multichain:1.0.0staging@O2"

[clone.InfinexGovernancePoints]
options.GP_SALT = "GP_1_0_0"
options.GP_DEPLOYER = "<%= settings.GP_DEPLOYER %>"
options.ACCOUNT_FACTORY = "<%= imports.InfinexMultichain.imports.infinex.contracts.AccountFactory.address %>"
options.FORWARDER = "<%= imports.InfinexMultichain.imports.infinex.contracts.Forwarder.address %>"
options.INX_USDC = "<%= imports.InfinexMultichain.imports.infinex.settings.USDC %>"
options.REWARDS_DURATION = "2419200"
source = "infinex-governance-points:2.0.0@stw"
target = "infinex-governance-points:2.0.0@stw"
depends = ["pull.InfinexMultichain"]

# ---------- Initialise GP Contracts  ---------- #

[invoke.upgrade]
target = ["InfinexGovernancePoints.GovernancePointsProxy"]
func = "upgradeTo"
args = ["<%= imports.InfinexGovernancePoints.contracts.GovernancePointsImplementation.address %>"]
depends = ["clone.InfinexGovernancePoints"]
factory.GovernancePointsProxy.abiOf = ["InfinexGovernancePoints.GovernancePointsImplementation"]
factory.GovernancePointsProxy.event = "Upgraded"
factory.GovernancePointsProxy.arg = 0
factory.GovernancePointsProxy.highlight = true
from = "<%= settings.GP_MULTI_SIG %>"

[invoke.GovernancePointsProxyInitialize]
target = ["InfinexGovernancePoints.GovernancePointsProxy"]
func = "initialize"
args = ["<%= settings.GP_DEPLOYER %>"]
depends = ["clone.InfinexGovernancePoints"]

# ---------- Setting Post deployment parameters  ---------- #

[invoke.addAuthorisedMinter]
target = ["GovernancePointsProxy"]
func = "addAuthorisedMinter"
args = [ "<%= settings.GP_TRUSTED_KEEPER %>"]
from = "<%= settings.GP_MULTI_SIG %>"
depends = ["invoke.upgrade"]

[invoke.addAuthorisedTransferer]
target = ["GovernancePointsProxy"]
func = "addAuthorisedTransferer"
args = [ "<%= settings.GP_TRUSTED_KEEPER %>"]
from = "<%= settings.GP_MULTI_SIG %>"
depends = ["invoke.upgrade"]