name = "infinex-multichain"
version = "1.0.0"
preset = "apps"
description = "Infinex App integrations"
#  pnpm cannon build infinex-multichain/staging/infinex-multichain-apps-ethereum.toml --chain-id 1 --private-key
#   CANNON_ETHERSCAN_API_URL=https://api.etherscan.io/api ./run pnpm cannon verify infinex-multichain:0.1.7@apps --chain-id 1  --api-key

[var.Deploy]
DEPLOYER = "0x3F768E3aC5eE75A2F39CFD7d72Eb3a40Bddb5ecB"
MULTI_SIG = "0x3F768E3aC5eE75A2F39CFD7d72Eb3a40Bddb5ecB"

[clone.infinex]
options.APPS_DEPLOYER = "<%= settings.DEPLOYER %>"
options.APPS_USDC = "0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48"
# Curve Stableswap Config
options.APPS_CRV_CURVE_STABLESWAP_FACTORY = "0x6A8cbed756804B16E05E741eDaBd5cB544AE21bf" 
source = "infinex:1.0.0@apps"
target = "infinex:1.0.0@apps"
