name = "infinex-multichain"
version = "1.0.0staging"
preset = "apps"
description = "Infinex App integrations"
#   pnpm cannon build infinex-multichain/staging/infinex-multichain-apps-blast.toml --chain-id 81457 --private-key 

[var.Deploy]
DEPLOYER = "0x3F768E3aC5eE75A2F39CFD7d72Eb3a40Bddb5ecB"
MULTI_SIG = "0x6298551D56F825B3b6c3350D32129Ffd3cFb198C"

[clone.infinexApps]
options.APPS_DEPLOYER = "<%= settings.DEPLOYER %>"
options.APPS_USDC = "0x06efdbff2a14a7c8e15944d1f4a48f9f95f663a4"
# Curve Stableswap Config
options.APPS_CRV_CURVE_STABLESWAP_FACTORY = "0xd2002373543Ce3527023C75e7518C274A51ce712" # Curve does not exist on this chain
source = "infinex:1.0.0@apps"
target = "infinex:1.0.0staging@apps"
tags = ["1.0.0staging"]

# invoke the transfer of ownership from the deployer to the multisig

[invoke.transferOwnershipAppRegistry]
target = ["infinexApps.AppRegistry"]
func = "transferOwnership"
args = ["<%= settings.MULTI_SIG %>"]
from = "<%= settings.DEPLOYER %>"

[invoke.transferOwnershipCurveStableSwapAppBeacon]
target = ["infinexApps.CRV.CurveStableSwapAppBeacon"]
func = "transferOwnership"
args = ["<%= settings.MULTI_SIG %>"]
from = "<%= settings.DEPLOYER %>"

# # # invoke the acceptance of the ownership transfer from the multisig

# [invoke.acceptOwnership]
# target = ["infinex.InfinexProtocolConfigBeacon"]
# func = "acceptOwnership"
# from = "<%= settings.MULTI_SIG %>"
# depends = ["invoke.transferOwnership"]