#  pnpm cannon build infinex-multichain/staging/infinex-curve-app-test.arbitrum.toml --chain-id 42161 --dry-run
#  pnpm cannon publish infinex-curve-app-test:1.1.0@curve-stableswap --chain-id 42161 --exclude-cloned
#  pnpm cannon verify infinex-curve-app-test:latest@curve-stableswap --chain-id 42161 --api-key

name = "infinex-curve-app-test"
version = "1.1.0"
preset = "curve-stableswap"
description = "Infinex App integration for Curve StableSwap"

[var.Deploy]
DEPLOYER = "0x6298551D56F825B3b6c3350D32129Ffd3cFb198C"

[clone.CurveStableSwap]
options.CURVE_STABLESWAP_SALT = "CURVE_STABLESWAP_1_1_0staging"
options.CURVE_STABLESWAP_OWNER = "<%= settings.DEPLOYER %>"
options.CURVE_STABLESWAP_USDC = "0xaf88d065e77c8cC2239327C5EDb3A432268e5831"
options.CURVE_STABLESWAP_FACTORY = "0x9AF14D26075f142eb3F292D5065EB3faa646167b"
source = "infinex:1.1.0@curve-stableswap"
target = "infinex:1.1.0@curve-stableswap"

# ---------- Add Supported Pools To App Beacon ---------- #
[var.SupportedPools]
USDCUSDE_POOL = "0x1c34204fcfe5314dcf53be2671c02c35db58b4e3"

[invoke.AddUSDCUSDEPool]
target = ["CurveStableSwap.CurveStableSwapAppBeacon"]
func = "setIsSupportedPool"
args = [
    "<%= settings.USDCUSDE_POOL %>",
    true,
]
fromCall.func = "owner"