#  pnpm cannon build infinex-app-registry-test/testnets/infinex-app-registry-test.ethereum-sepolia.toml --chain-id 11155111 --dry-run --upgrade-from
#  pnpm cannon publish infinex-app-registry-test:3.0.0@app-registry --chain-id 11155111 --exclude-cloned

name = "infinex-app-registry-test"
version = "3.0.0"
preset = "app-registry"
description = "Approved apps for the Infinex App Registry"

[pull.InfinexCoreTest]
source = "infinex-core-test:latest@core"

[pull.Curve]
source = "infinex-curve-app-test:latest@curve-stableswap"

# ---------- Add Apps ---------- #

[invoke.AddCurve]
target = ["InfinexCoreTest.infinex.AppRegistry"]
func = "setAppBeaconStatus"
args = [
    "<%= imports.Curve.imports.CurveStableSwap.contracts.CurveStableSwapAppBeacon.address %>",
    true,
]
fromCall.func = "owner"
